{"@t":"2024-09-17T19:27:52.4471136Z","@mt":"Erro ao obter validade do cartao","@l":"Error","@x":"MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication to host '129.148.59.75' for user 'aluno6' using method 'caching_sha2_password' failed with message: Access denied for user 'aluno6'@'%' to database 'humberto'\r\n ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user 'aluno6'@'%' to database 'humberto'\r\n   at MySql.Data.MySqlClient.MySqlStream.ReadPacketAsync(Boolean execAsync)\r\n   at MySql.Data.MySqlClient.NativeDriver.ReadPacketAsync(Boolean execAsync)\r\n   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacketAsync(Boolean execAsync)\r\n   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticationFailed(MySqlException ex)\r\n   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacketAsync(Boolean execAsync)\r\n   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ContinueAuthenticationAsync(Boolean execAsync, Byte[] data)\r\n   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.AuthenticateAsync(Boolean reset, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.NativeDriver.AuthenticateAsync(String authMethod, Boolean reset, Boolean execAsync)\r\n   at MySql.Data.MySqlClient.NativeDriver.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.NativeDriver.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.Driver.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.Driver.CreateAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.Driver.CreateAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriverAsync(Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.MySqlPool.GetConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)\r\n   at MySql.Data.MySqlClient.MySqlConnection.Open()\r\n   at Projeto1Bimestre.Services.CartaoService.ObterValidadeCartao(String numero) in C:\\Users\\humbe\\Desktop\\SextoSemestre\\LP1\\Projeto1Bimestre\\Projeto1Bimestre\\Services\\CartaoService.cs:line 69","@tr":"a4b5e3be13edf9ce1bcd7747ee1e02a9","@sp":"c6552ec699aa9282","SourceContext":"Projeto1Bimestre.Services.CartaoService","ActionId":"07178dd5-9be1-4606-a406-692370f09edc","ActionName":"Projeto1Bimestre.Controllers.CartoesController.ObterValidade (Projeto1Bimestre)","RequestId":"0HN6N9R46MASD:00000001","RequestPath":"/api/Cartoes/1111255516996632/valido","ConnectionId":"0HN6N9R46MASD"}
{"@t":"2024-09-17T19:27:52.5403441Z","@mt":"Erro ao realizar Conexão","@l":"Error","@x":"System.Exception: Authentication to host '129.148.59.75' for user 'aluno6' using method 'caching_sha2_password' failed with message: Access denied for user 'aluno6'@'%' to database 'humberto'\r\n   at Projeto1Bimestre.Services.CartaoService.ObterValidadeCartao(String numero) in C:\\Users\\humbe\\Desktop\\SextoSemestre\\LP1\\Projeto1Bimestre\\Projeto1Bimestre\\Services\\CartaoService.cs:line 86","@tr":"a4b5e3be13edf9ce1bcd7747ee1e02a9","@sp":"c6552ec699aa9282","SourceContext":"Projeto1Bimestre.Services.CartaoService","ActionId":"07178dd5-9be1-4606-a406-692370f09edc","ActionName":"Projeto1Bimestre.Controllers.CartoesController.ObterValidade (Projeto1Bimestre)","RequestId":"0HN6N9R46MASD:00000001","RequestPath":"/api/Cartoes/1111255516996632/valido","ConnectionId":"0HN6N9R46MASD"}
{"@t":"2024-09-17T19:27:52.5481670Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"System.Exception: Authentication to host '129.148.59.75' for user 'aluno6' using method 'caching_sha2_password' failed with message: Access denied for user 'aluno6'@'%' to database 'humberto'\r\n   at Projeto1Bimestre.Services.CartaoService.ObterValidadeCartao(String numero) in C:\\Users\\humbe\\Desktop\\SextoSemestre\\LP1\\Projeto1Bimestre\\Projeto1Bimestre\\Services\\CartaoService.cs:line 96\r\n   at Projeto1Bimestre.Controllers.CartoesController.ObterValidade(String cartao) in C:\\Users\\humbe\\Desktop\\SextoSemestre\\LP1\\Projeto1Bimestre\\Projeto1Bimestre\\Controllers\\CartoesController.cs:line 39\r\n   at lambda_method2(Closure, Object, Object[])\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)","@tr":"a4b5e3be13edf9ce1bcd7747ee1e02a9","@sp":"c6552ec699aa9282","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"0HN6N9R46MASD:00000001","RequestPath":"/api/Cartoes/1111255516996632/valido","ConnectionId":"0HN6N9R46MASD"}
{"@t":"2024-09-17T19:35:14.7775362Z","@mt":"Erro ao obter validade do cartao","@l":"Error","@x":"MySql.Data.MySqlClient.MySqlException (0x80004005): Invalid attempt to access a field before calling Read()\r\n   at MySql.Data.MySqlClient.ResultSet.get_Item(Int32 index)\r\n   at MySql.Data.MySqlClient.MySqlDataReader.GetFieldValue(Int32 index, Boolean checkNull)\r\n   at MySql.Data.MySqlClient.MySqlDataReader.GetValue(Int32 i)\r\n   at MySql.Data.MySqlClient.MySqlDataReader.get_Item(Int32 i)\r\n   at MySql.Data.MySqlClient.MySqlDataReader.get_Item(String name)\r\n   at Projeto1Bimestre.Services.CartaoService.ObterValidadeCartao(String numero) in C:\\Users\\humbe\\Desktop\\SextoSemestre\\LP1\\Projeto1Bimestre\\Projeto1Bimestre\\Services\\CartaoService.cs:line 82","@tr":"8e5165b50581b74452dd8b1a3db2fd09","@sp":"dae45f29ab0f8fd0","SourceContext":"Projeto1Bimestre.Services.CartaoService","ActionId":"d75067ce-1234-4635-af59-eb1319c5b74e","ActionName":"Projeto1Bimestre.Controllers.CartoesController.ObterValidade (Projeto1Bimestre)","RequestId":"0HN6N9VAUC8GL:00000001","RequestPath":"/api/Cartoes/3333932532432452/valido","ConnectionId":"0HN6N9VAUC8GL"}
{"@t":"2024-09-17T19:35:14.9679531Z","@mt":"Erro ao realizar Conexão","@l":"Error","@x":"System.Exception: Invalid attempt to access a field before calling Read()\r\n   at Projeto1Bimestre.Services.CartaoService.ObterValidadeCartao(String numero) in C:\\Users\\humbe\\Desktop\\SextoSemestre\\LP1\\Projeto1Bimestre\\Projeto1Bimestre\\Services\\CartaoService.cs:line 92","@tr":"8e5165b50581b74452dd8b1a3db2fd09","@sp":"dae45f29ab0f8fd0","SourceContext":"Projeto1Bimestre.Services.CartaoService","ActionId":"d75067ce-1234-4635-af59-eb1319c5b74e","ActionName":"Projeto1Bimestre.Controllers.CartoesController.ObterValidade (Projeto1Bimestre)","RequestId":"0HN6N9VAUC8GL:00000001","RequestPath":"/api/Cartoes/3333932532432452/valido","ConnectionId":"0HN6N9VAUC8GL"}
